### PR TITLE
Add typestub

### PR DESCRIPTION
**Pull request by tamuhey**
Based on [PEP 561](https://www.python.org/dev/peps/pep-0561/), I added type stubs into mojimoji.

The changes are as follows:

- add `mojimoji-stubs` directory which contains type stub file (ref: https://www.python.org/dev/peps/pep-0561/#stub-only-packages)
- add mypy to test the type stub
- refactor test

### CODE REVIEW

**Comment by ikuyamada** [comment]
@tamuhey Thank you for your PR! Do you also plan to distribute `mojimoji-stub` package on PyPI?

**Comment by tamuhey** [comment]
Of course!
But according to [PEP 561](https://www.python.org/dev/peps/pep-0561/#stub-only-packages), `mojimoji-stubs` is automatically bundled in `mojimoji` when it is packaged, so there is no need to publish `mojimoij-stubs` separately.

[PEP 561](https://www.python.org/dev/peps/pep-0561/#stub-only-packages): 

> ... the stubs can also be put in a separate package and distributed separately. Third parties can also find this method useful if they wish to distribute stub files. The name of the stub package MUST follow the scheme foopkg-stubs for type stubs for the package named foopkg. Note that for stub-only packages adding a py.typed marker is not needed since the name *-stubs is enough to indicate it is a source of typing information.

**Comment by tamuhey** [comment]
So I want to release next version of `mojimoji`, what do you think? @ikuyamada

**Comment by ikuyamada** [comment]
@tamuhey Thank you for the information and the contribution! It would be helpful for users to bundle the stub file, so I agree to release the next version of mojimoji.

**Comment by tamuhey** [comment]
I tried it with test pypi but it didn't work.
I'm sorry I misunderstood somthing.
I'll fix it in another PR.

**Pull request merged**
