### PR TITLE
Ci publish

### PR DESCRIPTION
**Pull request by tamuhey**
Build mojimoji for multi platform

### CODE REVIEW

**Comment by tamuhey** [comment]
I'm sorry, I created this PR by mistake.

**Comment by ikuyamada** [comment]
Hi @tamuhey,
I noticed that you have been working on this library to fix installation issues for several platforms.
I do not currently have time to spare for maintaining this project, so I highly appreciate your efforts!
However, I think creating separate `mojimoji2` on PyPI may be confusing for users because if I understand correctly, it provides equivalent functionality to `mojimoji`.
So I would appreciate it if you consider working on the code available on this repository.
Also, if you're okay with it, I can give you an access to this repository.

**Comment by tamuhey** [comment]
Thank you very much!
Of course it's best to work with this repository, so I'd be glad to have access permission.

**Comment by ikuyamada** [comment]
@tamuhey Thanks!
I sent an invitation to this repository.
If you create a PR, I review and merge it as soon as possible.
Looking forward to working with you!

**Comment by tamuhey** [comment]
Thanks! I close this PR for now, and I'll create another repository to fix this issue.

**Pull request closed without merging**
